name: Update facades-example Branch
on:
  push:
    branches:
      - "main"
    paths:
      - "facades-example/**"

jobs:
  deploy:
    name: Update facades-example Branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: facades-example
          FOLDER: facades-example
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
