name: Update facades-example Branch
on:
  push:
    branches:
      - "main"
    paths:
      - "facades-example/**"
      - ".github/workflows/facades-example.yml"

jobs:
  deploy:
    name: Update facades-example Branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Build
        run: |
          cd facades-example
          npm i
          npx ng build --aot
          git clean -xdf

      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: facades-example
          FOLDER: facades-example
          SQUASH_HISTORY: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
